### PR TITLE
Issue/2

### LINKED ISSUE #2: override fails when called with 0 paramters
Calling override without any parameters fails 

```
\Phlib\Config\override()

Fatal error: Uncaught TypeError: Return value of Phlib\Config\override() must be of the type array, null returned in /var/www/wft/vendor/phlib/config/src/Config.php on line 109
```

Discussed with @qubit05 and decided that the behaviour should be to throw an exception if override is called with fewer than two parameters.

### PR DESCRIPTION
**Pull request by awhale**
Fixes #2

### CODE REVIEW

**Review by qubit05 — APPROVED** [review]

File: src/Config.php [hunk 1]
```diff
@@ -87,6 +89,10 @@ function forget(array &$array, string $key): array
  */
 function override(...$arrays): array
```
Comment (Pudge601) [inline src/Config.php:90]: Would it not have been nicer to change this to

```
function override(array $baseArray, ...$arrays): array
```
?


Then you get rid of the `array_shift` below because we've already got the `$baseArray` as a simple required argument, and `$arrays` will always be a valid value to pass into the `foreach` (if called with only one argument, then `$arrays` is an empty array and the function just returns the untouched `$baseArray`).
